name: Nightly Build

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight (UTC)

env:
  POETRY_VERSION: "1.8.2"

jobs:
  backend-unit-tests:
    name: Run Backend Unit Tests
    uses: ./.github/workflows/python_test.yml
    with:
      python-versions: '["3.10", "3.11", "3.12"]'

  backend-integration-tests:
    name: Run Backend Integration Tests
    uses: ./.github/workflows/integration_tests.yml
    with:
      python-versions: '["3.10", "3.11", "3.12"]'

  run-nightly-build:
    name: Run Nightly Langflow Build
    needs: [backend-unit-tests, backend-integration-tests]
    uses: ./.github/workflows/release.yml
    with:
      release_package_base: false
      release_package_main: true
      build_docker_base: false
      build_docker_main: true
      create_release: false
      nightly_build: true